// Radar de Tendencias y Contenido IA - Professional Service Agent
// Rich data structures for trends, patterns, and 10-day content calendar

export async function scanTrends(niche = '', language = 'es') {
    await new Promise(resolve => setTimeout(resolve, 2500));
    const lowerNiche = niche.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");

    const data = nicheData[language]?.[lowerNiche] || nicheData[language]?.[findClosestKey(lowerNiche, language)];
    if (data) return data;

    return generateDynamicData(niche, language);
}

function findClosestKey(niche, lang) {
    const keys = Object.keys(nicheData[lang] || {});
    return keys.find(k => niche.includes(k) || k.includes(niche));
}

function generateDynamicData(niche, lang) {
    const isEs = lang === 'es';
    return {
        trends: generateTrends(niche, isEs),
        patterns: generatePatterns(niche, isEs),
        calendar: generateCalendar(niche, isEs)
    };
}

function generateTrends(niche, isEs) {
    const templates = isEs ? [
        { platform: 'YouTube', title: `Guía Completa de ${niche} en 2025`, format: 'Video largo (15-20min)', performance: 'high', views: '450K', engagement: '6.2%', velocity: 'trending', insight: 'Contenido evergreen que posiciona autoridad.' },
        { platform: 'TikTok', title: `3 Secretos de ${niche} que Nadie Te Cuenta`, format: 'Short 60s', performance: 'high', views: '1.2M', engagement: '9.1%', velocity: 'viral', insight: 'El formato "secreto" genera curiosidad inmediata.' },
        { platform: 'Instagram', title: `Errores Comunes en ${niche}`, format: 'Carrusel 8 slides', performance: 'high', views: '320K', engagement: '7.8%', velocity: 'growing', insight: 'El aprendizaje negativo tiene mayor retención.' },
        { platform: 'TikTok', title: `POV: Eres experto en ${niche}`, format: 'Short 30s', performance: 'high', views: '890K', engagement: '11.2%', velocity: 'viral', insight: 'El formato POV humaniza y genera identificación.' },
        { platform: 'YouTube', title: `${niche}: Antes vs Ahora`, format: 'Video comparativo', performance: 'medium', views: '180K', engagement: '5.4%', velocity: 'stable', insight: 'La nostalgia + progreso conecta emocionalmente.' },
        { platform: 'Instagram', title: `Tutorial Rápido: ${niche}`, format: 'Reel 90s', performance: 'high', views: '520K', engagement: '8.9%', velocity: 'trending', insight: 'Valor práctico inmediato es el rey del engagement.' },
        { platform: 'TikTok', title: `Lo que NO te dicen de ${niche}`, format: 'Storytime', performance: 'high', views: '2.1M', engagement: '12.3%', velocity: 'viral', insight: 'El morbo controlado dispara la viralidad.' },
        { platform: 'Web', title: `${niche}: Guía Definitiva 2025`, format: 'Artículo SEO', performance: 'medium', views: '45K', engagement: '3.2%', velocity: 'stable', insight: 'Tráfico orgánico de larga cola.' },
        { platform: 'Instagram', title: `Un día en mi vida: ${niche}`, format: 'Stories + Reel', performance: 'medium', views: '210K', engagement: '6.7%', velocity: 'growing', insight: 'El contenido lifestyle genera comunidad.' },
        { platform: 'YouTube', title: `Respondiendo Preguntas sobre ${niche}`, format: 'Q&A', performance: 'medium', views: '95K', engagement: '7.1%', velocity: 'stable', insight: 'Interacción directa fideliza la audiencia.' }
    ] : [
        { platform: 'YouTube', title: `Complete ${niche} Guide 2025`, format: 'Long-form (15-20min)', performance: 'high', views: '450K', engagement: '6.2%', velocity: 'trending', insight: 'Evergreen content that builds authority.' },
        { platform: 'TikTok', title: `3 ${niche} Secrets Nobody Tells You`, format: 'Short 60s', performance: 'high', views: '1.2M', engagement: '9.1%', velocity: 'viral', insight: '"Secret" format creates immediate curiosity.' }
    ];
    return templates;
}

function generatePatterns(niche, isEs) {
    return isEs ? [
        { pattern: 'Los videos que empiezan con una pregunta retórica tienen 2.8x más retención en los primeros 3 segundos', evidence: ['8 de 10 videos virales usan este hook', `Ejemplo: "¿Sabías que el 90% de ${niche} falla por esto?"`], recommendation: 'Abre con: [PREGUNTA PROVOCADORA] + [PAUSA 1s] + [RESPUESTA SORPRENDENTE]' },
        { pattern: 'El contenido "anti-gurú" (desmitificando expertos) genera 3.4x más comentarios', evidence: ['Los threads de debate tienen 45% más alcance', 'La polarización controlada activa el algoritmo'], recommendation: `Crea contenido tipo "Lo que los expertos de ${niche} NO quieren que sepas"` },
        { pattern: 'Los carruseles con exactamente 7-8 slides tienen el mejor ratio de guardados', evidence: ['Menos de 5 slides = bajo valor percibido', 'Más de 10 = fatiga del usuario'], recommendation: 'Estructura: Hook → 5-6 puntos de valor → CTA final' },
        { pattern: 'Publicar entre 18:00-21:00 (hora local) aumenta el engagement un 34%', evidence: ['Peak de usuarios activos en todas las plataformas', 'Menor competencia de marcas (publican en horario laboral)'], recommendation: 'Programa tus posts para las 19:30 como punto óptimo' },
        { pattern: 'El formato "Mito vs Realidad" supera en 2.1x al contenido educativo tradicional', evidence: ['Activa el sesgo de corrección del espectador', 'Genera comentarios del tipo "yo pensaba que..."'], recommendation: `Crea: "5 Mitos de ${niche} que sigues creyendo"` }
    ] : [
        { pattern: 'Videos starting with rhetorical questions have 2.8x more retention in first 3 seconds', evidence: ['8/10 viral videos use this hook'], recommendation: 'Open with: [PROVOCATIVE QUESTION] + [1s PAUSE] + [SURPRISING ANSWER]' }
    ];
}

function generateCalendar(niche, isEs) {
    const today = new Date();
    return isEs ? [
        { day: 1, date: formatDate(today, 0), platform: 'Instagram', format: 'Reel 60s', pillar: 'Educativo', theme: `Introducción a ${niche}`, hook: `🚨 El 90% de personas en ${niche} comete este error fatal`, copy: `¿Sabías que la mayoría fracasa en ${niche} por no entender esto?\n\nDespués de analizar cientos de casos, descubrí el patrón que separa a los que triunfan de los que abandonan.\n\n✅ No es talento\n✅ No es dinero\n✅ No es suerte\n\nEs algo mucho más simple (y está en el video).\n\n¿Tú también cometías este error? 👇`, cta: 'Guarda este post para no olvidarlo ☑️', hashtags: [`#${niche.replace(/\s/g, '')}`, '#aprendizaje', '#tips', '#viral', '#foryou'], suggestedAudio: 'Trending: "Dramatic strings reveal"', visualDescription: 'Hook text overlay → Tu cara hablando → Gráfico simple → CTA final' },
        { day: 2, date: formatDate(today, 1), platform: 'TikTok', format: 'Short 45s', pillar: 'Entretenimiento', theme: 'Mitos desmontados', hook: `POV: Descubres que todo lo que sabías de ${niche} es mentira`, copy: `Mito: "Necesitas años de experiencia"\nRealidad: Necesitas 3 meses de práctica enfocada\n\nMito: "Es muy caro empezar"\nRealidad: Puedes empezar con 0€ usando estas herramientas\n\nMito: "Ya hay demasiada competencia"\nRealidad: El 95% abandona en 3 meses\n\n¿Cuál de estos mitos te tenía paralizado?`, cta: 'Sígueme para más verdades incómodas 🔥', hashtags: ['#mitos', '#verdad', '#fyp', '#viral', '#mindset'], suggestedAudio: 'Trending: "Oh no" remix', visualDescription: 'Green screen con texto → Reacción facial exagerada → Transiciones rápidas' },
        { day: 3, date: formatDate(today, 2), platform: 'Instagram', format: 'Carrusel 8 slides', pillar: 'Educativo', theme: 'Guía paso a paso', hook: `La guía de ${niche} que hubiera querido tener hace 2 años`, copy: `He condensado 2 años de errores en 8 slides.\n\nSlide 2: Por dónde empezar (sin gastar dinero)\nSlide 3: Los 3 pilares fundamentales\nSlide 4-6: Errores que te están frenando\nSlide 7: El framework que nadie enseña\nSlide 8: Tu plan de acción para esta semana\n\n¿En qué slide te quedaste más tiempo? 👇`, cta: 'Guarda + Comparte con alguien que lo necesita', hashtags: [`#${niche.replace(/\s/g, '')}`, '#guia', '#tutorial', '#aprende', '#tips'], suggestedAudio: 'N/A (Carrusel)', visualDescription: 'Slide 1: Hook bold → Slides 2-7: Iconos + texto minimal → Slide 8: CTA con flecha' },
        { day: 4, date: formatDate(today, 3), platform: 'YouTube', format: 'Video 12min', pillar: 'Autoridad', theme: 'Caso de estudio', hook: `Cómo pasé de 0 a resultados en ${niche} (con pruebas)`, copy: `En este video te muestro exactamente el proceso que seguí, con números reales y errores incluidos.\n\n⏱️ Timestamps:\n0:00 - Mi situación inicial\n2:30 - El primer error (casi abandono)\n5:00 - El cambio de estrategia\n8:00 - Resultados mes a mes\n10:30 - Lo que haría diferente hoy\n\nSi estás empezando en ${niche}, este video te va a ahorrar meses de frustración.`, cta: 'Suscríbete y activa la 🔔 para más casos reales', hashtags: [`#${niche.replace(/\s/g, '')}`, '#casodeestudio', '#tutorial'], suggestedAudio: 'Background: Lo-fi chill', visualDescription: 'Intro dinámica → Screenshots reales → Gráficos de progreso → Outro con CTA' },
        { day: 5, date: formatDate(today, 4), platform: 'TikTok', format: 'Short 30s', pillar: 'Comunidad', theme: 'Respuesta a comentario', hook: `"${niche} ya no funciona en 2025" - Mi respuesta:`, copy: `Alguien me comentó esto y tengo que responder.\n\nNo es que no funcione...\nEs que la mayoría sigue usando estrategias de 2020.\n\nLo que SÍ funciona ahora:\n→ [Punto 1]\n→ [Punto 2]\n→ [Punto 3]\n\n¿Tú qué opinas? ¿Funciona o no?`, cta: 'Comenta tu experiencia 👇', hashtags: ['#respuesta', '#debate', '#fyp', '#viral'], suggestedAudio: 'Original Sound', visualDescription: 'Stitch con el comentario → Tu reacción → Puntos con texto overlay' },
        { day: 6, date: formatDate(today, 5), platform: 'Instagram', format: 'Reel 90s', pillar: 'Educativo', theme: 'Tutorial práctico', hook: `Aprende ${niche} en 90 segundos (método probado)`, copy: `No necesitas un curso de 500€.\nNo necesitas 3 meses.\n\nNecesitas estos 4 pasos:\n\n1️⃣ [Paso 1 - 15s]\n2️⃣ [Paso 2 - 20s]\n3️⃣ [Paso 3 - 25s]\n4️⃣ [Paso 4 - 20s]\n\nAhora ya no tienes excusa.\n\n¿Por cuál paso empezarás hoy?`, cta: 'Guarda para hacerlo este finde 📌', hashtags: ['#tutorial', '#aprende', '#facil', '#rapido', '#howto'], suggestedAudio: 'Trending: Upbeat tutorial music', visualDescription: 'Split screen: tú + acción → Números grandes → Transiciones suaves' },
        { day: 7, date: formatDate(today, 6), platform: 'Instagram', format: 'Stories (5 slides)', pillar: 'Comunidad', theme: 'Q&A interactivo', hook: `Pregúntame lo que quieras sobre ${niche}`, copy: `Story 1: "Hoy respondo TODAS tus preguntas sobre ${niche}"\nStory 2: Encuesta "¿Eres principiante o avanzado?"\nStory 3: Caja de preguntas\nStory 4: Respuesta a pregunta popular\nStory 5: "Mañana subo las mejores respuestas"`, cta: 'Usa la caja de preguntas ⬆️', hashtags: [], suggestedAudio: 'N/A (Stories)', visualDescription: 'Fondo degradado → Stickers interactivos → Tu cara respondiendo' },
        { day: 8, date: formatDate(today, 7), platform: 'TikTok', format: 'Short 60s', pillar: 'Entretenimiento', theme: 'Trend adaptation', hook: `Este trend pero aplicado a ${niche} 😂`, copy: `[Adaptar trend viral actual al nicho]\n\nLa clave es mantener el formato exacto del trend pero cambiar el contenido a tu especialidad.\n\nEsto aprovecha:\n→ El momentum del algoritmo\n→ La familiaridad del formato\n→ La sorpresa del twist`, cta: 'Sígueme para más trends adaptados', hashtags: ['#trend', '#viral', '#fyp', '#humor'], suggestedAudio: 'El audio del trend actual', visualDescription: 'Replicar exactamente el formato del trend con tu contenido' },
        { day: 9, date: formatDate(today, 8), platform: 'Instagram', format: 'Post estático', pillar: 'Motivacional', theme: 'Quote + reflexión', hook: `La verdad sobre ${niche} que nadie quiere escuchar`, copy: `"El éxito en ${niche} no es un sprint.\nEs una maratón donde el 95% abandona en el km 5."\n\nLlevo [X tiempo] en esto y he visto a cientos empezar.\n\n¿Sabes cuántos siguen activos?\nMenos del 5%.\n\n¿La diferencia?\nNo es talento.\nNo es dinero.\nNo es suerte.\n\nEs consistencia.\n\nEtiqueta a alguien que necesita escuchar esto.`, cta: 'Etiqueta a quien necesita leer esto 👇', hashtags: ['#motivacion', '#consistencia', '#exito', '#mentalidad'], suggestedAudio: 'N/A', visualDescription: 'Fondo minimalista → Tipografía bold → Tu firma/logo' },
        { day: 10, date: formatDate(today, 9), platform: 'YouTube', format: 'Short 60s', pillar: 'Educativo', theme: 'Resumen semanal', hook: `Lo mejor de ${niche} esta semana (resumen rápido)`, copy: `Esta semana pasaron 3 cosas importantes:\n\n1️⃣ [Novedad/Noticia 1]\n2️⃣ [Tendencia emergente]\n3️⃣ [Herramienta/Recurso nuevo]\n\nSi te perdiste algo, este video te pone al día en 60 segundos.\n\n¿Cuál te pareció más interesante?`, cta: 'Suscríbete para el resumen de cada semana', hashtags: [`#${niche.replace(/\s/g, '')}`, '#resumen', '#noticias', '#actualidad'], suggestedAudio: 'Upbeat news-style', visualDescription: 'Intro rápida → 3 puntos con iconos → Outro con suscripción' }
    ] : generateCalendarEN(niche, today);
}

function generateCalendarEN(niche, today) {
    return [
        { day: 1, date: formatDate(today, 0), platform: 'Instagram', format: 'Reel 60s', pillar: 'Educational', theme: `Introduction to ${niche}`, hook: `🚨 90% of people in ${niche} make this fatal mistake`, copy: `Did you know most people fail at ${niche} because they don't understand this?\n\nAfter analyzing hundreds of cases, I discovered the pattern that separates winners from quitters.\n\n✅ It's not talent\n✅ It's not money\n✅ It's not luck\n\nIt's something much simpler.\n\nWere you making this mistake too? 👇`, cta: 'Save this post for later ☑️', hashtags: [`#${niche.replace(/\s/g, '')}`, '#learning', '#tips', '#viral'], suggestedAudio: 'Trending: Dramatic reveal', visualDescription: 'Hook text → Face talking → Simple graphic → Final CTA' }
    ];
}

function formatDate(base, offset) {
    const d = new Date(base);
    d.setDate(d.getDate() + offset);
    return d.toISOString().split('T')[0];
}

const nicheData = {
    es: {
        'ia medica': {
            trends: [
                { platform: 'YouTube', title: '¿Puede la IA Detectar Cáncer Mejor que un Médico?', format: 'Video largo 18min', performance: 'high', views: '2.3M', engagement: '7.8%', velocity: 'viral', insight: 'El conflicto humano vs IA genera debate masivo y shares.' },
                { platform: 'TikTok', title: 'Esta App Detecta 47 Enfermedades con una Selfie', format: 'Short 45s', performance: 'high', views: '4.1M', engagement: '12.4%', velocity: 'viral', insight: 'Tech accesible + utilidad práctica = viralidad garantizada.' },
                { platform: 'Instagram', title: 'Gadgets Médicos que Parecen del Futuro', format: 'Reel 60s', performance: 'high', views: '890K', engagement: '9.2%', velocity: 'trending', insight: 'Lo visual y futurista captura atención instantánea.' },
                { platform: 'TikTok', title: 'Un Robot Me Operó (Mi Experiencia Real)', format: 'Storytime 90s', performance: 'high', views: '3.2M', engagement: '11.1%', velocity: 'viral', insight: 'Experiencias personales reales superan al contenido genérico.' },
                { platform: 'YouTube', title: 'IA para Médicos: Ahorra 3 Horas Diarias', format: 'Tutorial 25min', performance: 'high', views: '520K', engagement: '6.5%', velocity: 'trending', insight: 'Productividad práctica es el gancho #1 para profesionales.' },
                { platform: 'Instagram', title: 'El Futuro del Diagnóstico: IA + Wearables', format: 'Carrusel 10 slides', performance: 'medium', views: '210K', engagement: '5.8%', velocity: 'stable', insight: 'Contenido evergreen para early adopters tecnológicos.' },
                { platform: 'TikTok', title: 'ChatGPT Me Diagnosticó Antes que Mi Médico', format: 'Short controvertido', performance: 'high', views: '5.7M', engagement: '14.2%', velocity: 'viral', insight: 'La controversia controlada dispara el algoritmo.' },
                { platform: 'Web', title: 'IA y Ética Médica: El Gran Debate de 2025', format: 'Artículo largo', performance: 'medium', views: '85K', engagement: '4.1%', velocity: 'stable', insight: 'Posicionamiento SEO para búsquedas de autoridad.' },
                { platform: 'YouTube', title: 'Radiólogo vs IA: ¿Quién Gana?', format: 'Video comparativo', performance: 'high', views: '1.8M', engagement: '8.9%', velocity: 'trending', insight: 'El formato "versus" genera expectativa y retención.' },
                { platform: 'Instagram', title: '5 Apps de IA que Todo Médico Debería Usar', format: 'Reel lista', performance: 'high', views: '450K', engagement: '7.3%', velocity: 'trending', insight: 'Las listas numeradas tienen mejor CTR en feed.' }
            ],
            patterns: [
                { pattern: 'El contenido que muestra IA vs Humanos genera 3.5x más comentarios de debate', evidence: ['Los videos "¿Puede la IA reemplazar médicos?" tienen el mayor engagement', 'Los comentarios polarizados activan el algoritmo de recomendación'], recommendation: 'Crea contenido tipo "IA detecta X mejor que especialistas" con conclusión equilibrada' },
                { pattern: 'Los tutoriales de productividad médica tienen 2.8x más guardados que el contenido teórico', evidence: ['Los videos de "ahorra 2h de papeleo" superan a las explicaciones técnicas', 'El ROI tangible es el principal motivador de acción'], recommendation: 'Enfócate en el BENEFICIO PRÁCTICO, no en la tecnología' },
                { pattern: 'El contenido de detección temprana tiene el mayor ratio de shares (4.2x promedio)', evidence: ['La gente comparte para "salvar vidas" de sus conocidos', 'El factor emocional supera al informativo'], recommendation: 'Incluye siempre un ángulo de "esto puede salvar una vida"' },
                { pattern: 'Los gadgets médicos visuales superan al software abstracto en 2.1x views', evidence: ['Lo táctil y futurista es más "instagrameable"', 'Los productos físicos se entienden más rápido que las apps'], recommendation: 'Cuando hables de software, muestra siempre la interfaz o un caso real' },
                { pattern: 'Publicar contenido médico los martes y miércoles a las 20:00 aumenta el alcance 28%', evidence: ['Los profesionales de salud revisan RRSS después del trabajo', 'Menos competencia de contenido lifestyle esos días'], recommendation: 'Programa tu contenido médico para mar/mié 20:00-21:00' }
            ],
            calendar: [
                { day: 1, date: '2024-12-23', platform: 'Instagram', format: 'Reel 60s', pillar: 'Educativo', theme: 'Intro a IA médica', hook: '🚨 Esta app detecta melanomas con 95% de precisión (y es gratis)', copy: 'El cáncer de piel es el más común del mundo.\nPero también uno de los más tratables si se detecta a tiempo.\n\nEl problema: la mayoría no va al dermatólogo hasta que es tarde.\n\nLa solución: SkinVision.\n\n✅ Analiza lunares en segundos con IA\n✅ Misma tecnología que usan especialistas\n✅ Disponible gratis en iOS y Android\n\nYo la uso cada mes para revisar mis lunares.\n\n¿Conocías esta tecnología?\nCuéntame en comentarios 👇', cta: 'Guarda este post para revisarlo después ☑️', hashtags: ['#salud', '#tecnologia', '#prevencion', '#IA', '#skincare', '#cancer', '#dermatologia'], suggestedAudio: 'Trending: Dramatic reveal strings', visualDescription: 'Split screen: selfie de lunar → resultado de la app → tu cara explicando → CTA' },
                { day: 2, date: '2024-12-24', platform: 'TikTok', format: 'Short 45s', pillar: 'Entretenimiento', theme: 'IA vs Médicos', hook: 'POV: La IA detecta tu enfermedad antes que 3 médicos', copy: 'Historia real:\n\nUna mujer fue a 3 médicos.\nNinguno encontró nada.\n\nSubió sus síntomas a una IA de diagnóstico.\nResultado: posible enfermedad de Lyme.\n\nFue al hospital.\nTest: POSITIVO.\n\n¿Es la IA más lista que los médicos?\nNo.\n\nPero puede analizar millones de casos en segundos.\n\n¿Tú confiarías en una IA para tu diagnóstico?', cta: 'Sígueme para más historias así 🔥', hashtags: ['#IA', '#salud', '#medicina', '#tecnologia', '#viral', '#fyp'], suggestedAudio: 'Oh no / Dramatic sound', visualDescription: 'Green screen con noticias → Tu reacción → Texto overlay con datos' },
                { day: 3, date: '2024-12-25', platform: 'Instagram', format: 'Carrusel 8 slides', pillar: 'Educativo', theme: 'Herramientas IA', hook: '8 herramientas de IA que todo médico debería conocer en 2025', copy: 'He probado más de 50 herramientas de IA para medicina.\n\nEstas 8 son las que realmente uso:\n\n1️⃣ Notion AI - Notas clínicas\n2️⃣ Otter.ai - Transcripción consultas\n3️⃣ Consensus - Búsqueda papers\n4️⃣ Glass.health - Diagnóstico diferencial\n5️⃣ Nabla - Documentación automática\n6️⃣ Abridge - Resumen conversaciones\n7️⃣ Viz.ai - Análisis imágenes\n8️⃣ Suki - Asistente por voz\n\n¿Cuál vas a probar primero?', cta: 'Guarda + envía a un colega que lo necesita', hashtags: ['#medicina', '#IA', '#productividad', '#medicos', '#herramientas', '#tecnologia'], suggestedAudio: 'N/A (Carrusel)', visualDescription: 'Slide 1: Hook llamativo → Slides 2-8: Logo + 1 beneficio → Slide 9: CTA' },
                { day: 4, date: '2024-12-26', platform: 'YouTube', format: 'Video 15min', pillar: 'Autoridad', theme: 'Tutorial profundo', hook: 'Cómo uso IA para ahorrar 3 horas diarias de papeleo médico', copy: 'El papeleo es el enemigo #1 de los médicos.\n\nEn este video te muestro exactamente mi flujo de trabajo:\n\n⏱️ 0:00 - El problema (burnout administrativo)\n⏱️ 2:30 - Mi stack de herramientas IA\n⏱️ 6:00 - Demo en tiempo real\n⏱️ 10:00 - Resultados: antes vs después\n⏱️ 13:00 - Cómo implementarlo en tu clínica\n\nSi eres médico y odias el papeleo, este video te cambia la vida.', cta: 'Suscríbete para más productividad médica 🔔', hashtags: ['#medicina', '#IA', '#productividad', '#tutorial'], suggestedAudio: 'Lo-fi study beats', visualDescription: 'Intro dinámica → Screencast → Tu cara en esquina → Gráficos de ahorro tiempo' },
                { day: 5, date: '2024-12-27', platform: 'TikTok', format: 'Short 60s', pillar: 'Comunidad', theme: 'Debate ético', hook: '"La IA nunca reemplazará a los médicos" - ¿Estás seguro?', copy: 'Me dejaron este comentario.\nY tengo que responder.\n\n¿Reemplazar? Probablemente no.\n¿Hacer el trabajo de 10 médicos? Ya lo está haciendo.\n\nEjemplo real:\nUn algoritmo en un hospital de Londres analiza 50,000 mamografías.\nTiempo: 3 minutos.\nPrecisión: 94.5%\n\nUn radiólogo humano:\nTiempo: 200 horas.\nPrecisión: 88%.\n\n¿Qué opinas tú?\n¿Colaboración o competencia?', cta: 'Comenta tu opinión 👇', hashtags: ['#IA', '#medicina', '#debate', '#futuro', '#tecnologia', '#fyp'], suggestedAudio: 'Original / Debate sound', visualDescription: 'Stitch con comentario → Datos en pantalla → Tu cara reflexionando' },
                { day: 6, date: '2024-12-28', platform: 'Instagram', format: 'Reel 90s', pillar: 'Educativo', theme: 'Tendencias 2025', hook: '5 formas en que la IA cambiará la medicina en 2025', copy: 'El futuro de la medicina ya llegó.\n\nEstas 5 tendencias van a explotar en 2025:\n\n1️⃣ Diagnóstico por voz (Siri detectando enfermedades)\n2️⃣ Wearables predictivos (tu reloj predice infartos)\n3️⃣ Cirugía robótica autónoma\n4️⃣ Medicina personalizada por ADN + IA\n5️⃣ Asistentes virtuales de salud mental\n\n¿Cuál te parece más impactante?\n¿Cuál te da más miedo?\n\nDéjamelo en comentarios 👇', cta: 'Sígueme para estar al día con la IA médica', hashtags: ['#IA', '#medicina', '#futuro', '#2025', '#tecnologia', '#salud', '#tendencias'], suggestedAudio: 'Epic/Futuristic vibe', visualDescription: 'Intro con glitch → 5 puntos con iconos futuristas → Tu predicción → CTA' },
                { day: 7, date: '2024-12-29', platform: 'Instagram', format: 'Stories 6 slides', pillar: 'Comunidad', theme: 'Q&A interactivo', hook: 'Pregúntame lo que quieras sobre IA médica', copy: 'Story 1: "Hoy respondo TODAS tus dudas sobre IA y medicina"\nStory 2: Encuesta: "¿Confiarías en un diagnóstico de IA?"\nStory 3: Quiz: "¿Cuántas enfermedades puede detectar una IA?" (A: 10, B: 100, C: +1000)\nStory 4: Caja de preguntas\nStory 5: Respondo en directo\nStory 6: "Mañana subo las mejores respuestas al feed"', cta: 'Usa la caja de preguntas ⬆️', hashtags: [], suggestedAudio: 'N/A', visualDescription: 'Fondo temático médico → Stickers interactivos → Tu cara respondiendo' },
                { day: 8, date: '2024-12-30', platform: 'TikTok', format: 'Short 30s', pillar: 'Entretenimiento', theme: 'Trend adaptado', hook: 'El trend de "medicina" pero con IA', copy: '[Adaptar trend viral de la semana]\n\nEjemplo si el trend es "Tell me X without telling me X":\n\n"Tell me you work in AI healthcare without telling me you work in AI healthcare"\n\n→ Mi smartwatch me avisa antes que el médico\n→ Tengo 5 apps de diagnóstico en el móvil\n→ Le pregunto a ChatGPT antes que al farmacéutico', cta: 'Sígueme para más 🤣', hashtags: ['#trend', '#medicina', '#IA', '#humor', '#fyp', '#viral'], suggestedAudio: 'Audio del trend actual', visualDescription: 'Replicar formato del trend con contenido de IA médica' },
                { day: 9, date: '2024-12-31', platform: 'Instagram', format: 'Post imagen', pillar: 'Motivacional', theme: 'Reflexión de año', hook: 'Lo que aprendí de la IA médica en 2024', copy: '2024 fue el año en que la IA médica dejó de ser ciencia ficción.\n\n📊 Lo que pasó:\n- 47 apps de IA aprobadas por la FDA\n- Primer diagnóstico de cáncer 100% por IA\n- 2.3M de consultas asistidas por IA en España\n\n💡 Lo que aprendí:\n- La IA no reemplaza médicos, los potencia\n- La resistencia al cambio es el mayor obstáculo\n- Los que aprenden ahora, lideran mañana\n\n2025 será todavía más salvaje.\n¿Estás preparado?', cta: 'Comparte si crees que la IA cambiará la medicina 🚀', hashtags: ['#2024', '#IA', '#medicina', '#reflexion', '#futuro', '#tecnologia'], suggestedAudio: 'N/A', visualDescription: 'Diseño minimalista → Estadísticas destacadas → Tu foto pequeña → Logo' },
                { day: 10, date: '2025-01-01', platform: 'YouTube', format: 'Short 60s', pillar: 'Educativo', theme: 'Predicciones 2025', hook: '🔮 Mis 3 predicciones de IA médica para 2025', copy: 'Predicción 1: Apple Watch detectará AFIB con 99% precisión\n→ Ya están trabajando en ello\n\nPredicción 2: Un chatbot de salud mental será aprobado como "tratamiento"\n→ Los ensayos clínicos están en fase 3\n\nPredicción 3: China superará a USA en patentes de IA médica\n→ Ya van 2:1 en 2024\n\n¿Cuál crees que se cumplirá?\n¿Cuál es tu predicción?', cta: 'Suscríbete para ver si acerté 🎯', hashtags: ['#2025', '#predicciones', '#IA', '#medicina', '#futuro'], suggestedAudio: 'Futuristic whoosh', visualDescription: 'Bola de cristal intro → 3 predicciones con iconos → Tu cara apostando → CTA' }
            ]
        }
    },
    en: {}
};
